### ISSUE TITLE
UnboundLocalError: local variable 'uiFeedback' referenced before assignment

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanage#2]
Each time i use **e** or **e a** options on Arch / Manjaro i have such error:

![image](https://user-images.githubusercontent.com/47599989/62793812-2dc4ff00-badb-11e9-84c6-15382ec7cb31.png)

Although if you continue and ignore it, then relaunch script everything works ok...

```
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.2.4-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.11
WM: Deepin WM
python: 3.7.4-1
```

**Comment by Goli4thus** [comment]
Yeah that is a bug caused while terminal color support is disabled.
Fixed now, so please update and try again.

**Comment by keybreak** [comment]
Thx, it's fine now :+1:
