### ISSUE TITLE
[Suggestion] Simple way to drop termcolor

### ISSUE THREAD

**Issue by keybreak** [Goli4thus/linvstmanage#3]
Maybe it's a good idea to drop **termcolor** dependency, since you need just 4 colors you could  simply use escaped ANSI:
https://python-forum.io/Thread-Colored-text-output-in-python-3?pid=43997#pid43997

**Comment by Goli4thus** [comment]
Better late than never: 7329bf11e981f9bc1e7bb8467e7eac4d8c5cd22e
Thanks for the suggestion!

**Comment by keybreak** [comment]
Cool! :)

I can't thank you enough for your script, really helped me out on this path:
https://github.com/keybreak/linux-vst-compatibility-list
https://keybreak.github.io/linux-vst-compatibility-list/

Although there's way to go still to test my personal list and once i'll finish i'll open user-db and pr, but maybe you'll find it helpful now already ;)
